services:
  - type: web
    name: stcs-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
