; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Configuracion objetivo para Waveshare ESP32-S3-Touch-LCD-1.46.
; La placa comprada incorpora pantalla redonda 412x412, Wi-Fi, 16 MB Flash y 8 MB PSRAM.
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.partitions = huge_app.csv

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D STCS_DEVICE_ID=\"STCS-ESP32-001\"
  -D STCS_SCREEN_WIDTH=412
  -D STCS_SCREEN_HEIGHT=412

lib_deps =
  bblanchon/ArduinoJson@^7.4.2
